### PR TITLE
I would like to merge changes 

### PR DESCRIPTION
**Pull request by ghost**
So here's what we have done today. 
We started writing issues for the collision detection algorithm and quickly ran into some problems with the algorithm. Don't forget that the algorithm we're using keeps track of not only future collisions, but also past collisions. As a result of this fact we needed to figure out a solution to it. We had started to write tests, but ran into those fatal errors. We also ran into the problem of multiple planes coming into the PA and found a solution to that as well. (Read Ben's email) We finally started to stub out our methods in the actual files to start tests from them. We wrote a few issues on a google doc, which we will send to John and Jesse to add to and/or start writing unit tests if they want.

John- Jesse -> If you want to start writing unit tests for those issues up on the google doc, you're more then welcome to, but make a note saying you're working on it so that no one works on the same section. We decided that the collision detection method just returns true or false based on whether there is a collision or not. The sorting of the collisions will be done in the plane manager. I am sure you will have questions, so let us know. Since we were able to sort out the algorithm even better today with some tests, tomorrow the issues and test should cook.

### CODE REVIEW

**Comment by auroraaxela** [comment]
When you refer to "past collisions" as ones that would have happened behind
the plane, are those not "negative" vectors? We shouldn't even see anything
behind the plane; that flight path shouldn't even exist anymore, I would
think. Am I misunderstanding you?

**Comment by ghost** [comment]
We don't, but the algorithm does. We ran into the problem of getting hits even when they were supposed to miss, what we figured out was that they were colliding in the past. so in our email we made a note of it so that when they are writing test cases they don't get confused by those cases

**Comment by auroraaxela** [comment]
Ultimately we'll have to eliminate those cases from existence. But ok.

**Comment by bcdean03** [comment]
So basically the algorithm takes into affect the negative numbers as well based on the direction. That's just how the algorithm works. So we needed to take those issues into account when we were writing out some cases for our tests. In the implementation we are going to have to disregard those, which we talked about in our discussions.Thank you for revealing that breakdown in our communications though.

**Comment by bcdean03** [comment]
This is Dean

**Comment by auroraaxela** [comment]
Copy that. From my perspective:  The tests should never see those past
collisions, because once the implementation finds them (via the negatives),
the implementation will (should) disregard them. That being said, I think
the unittest doesn't necessarily need to deal with past collisions, because
the implementation ultimately should handle it internally and return the
same true/false collision result/data.

That's just my two cents. Thanks guys!

**Pull request merged**
